version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: Install Package
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[dev] coveralls
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            mkdir test-repoorts
            set -x
            pytest \
              --strict \
              --cov=openbci_interface \
              --junitxml=test-reports/junit.xml \
              tests
            cat .coverage
            sed -i "s|venv/lib/python3.6/site-packages|src|g" .coverage
            cat .coverage
            COVERALLS_REPO_TOKEN="${COVERALLS_REPO_TOKEN}" coveralls
      - run:
          name: Style Check
          command: |
            . venv/bin/activate
            flake8 src

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - test
